### PR TITLE
Fix Sun label is not shown when large FOV and with JPL emphem

### LINKED ISSUE #4076: No label for the Sun
It appears the label for the Sun has vanished. See the screenshot below:

bild

Current master, built with Qt6.7.1 on Windows 10.

None of the skycultures show a label for the Sun.

### PR DESCRIPTION
**Pull request by henrysky**
Fix Sun label is not shown when large FOV and with JPL emphem

Fixes #4076 

### Screenshots (if appropriate):

Screenshot 2025-01-13 at 8 35 55 PM

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: MacOS 15.2
* Graphics Card: Apple M3

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/core/modules/Planet.cpp [hunk 1]
```diff
@@ -1768,7 +1768,7 @@ QVector<const Planet*> Planet::getCandidatesForShadow() const
 	return res;
 }
 
-void Planet::computePosition(const StelObserver *observer, const double dateJDE, const Vec3d &aberrationPush)
+void Planet::computePosition(const StelObserver *observer, const double dateJDE, const Vec3d &aberrationPush)  // heliocentric
```
Comment (10110111) [inline src/core/modules/Planet.cpp:1771]: This comment should be part of the docs in the header.

Comment (henrysky) [reply src/core/modules/Planet.cpp]: fixed

**Review by alex-w — APPROVED** [review]
Thanks for quick fix!
