### PR TITLE
Don't load any high level star catalog if a lower level star catalog is missing

### LINKED ISSUE #4181: Stellarium Weekly Snapshot crashes when starting on a low configuration computer with Windows 10
### Actual Behaviour
It seems to have crashed while loading the exoplanet plug-in.

[log.txt](https://github.com/user-attachments/files/19120707/log.txt)

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

### PR DESCRIPTION
**Pull request by henrysky**
Don't load any high level star catalog if a lower level star catalog is missing. Warning is provided, telling user a star catalog is found but not loaded because a lower level star catalog is missing.

Fixes #4181

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: MacOS 15
* Graphics Card: Apple M3

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/core/modules/StarMgr.cpp [hunk 1]
```diff
@@ -624,10 +631,11 @@ void StarMgr::loadData(QVariantMap starsConfig)
 	qInfo() << "Loading star data ...";
 
 	catalogsDescription = starsConfig.value("catalogs").toList();
+	bool hasFailed = false;
 	foreach (const QVariant& catV, catalogsDescription)
 	{
 		QVariantMap m = catV.toMap();
-		checkAndLoadCatalog(m);
+		hasFailed = not checkAndLoadCatalog(m, not hasFailed);
```
Comment (10110111) [inline src/core/modules/StarMgr.cpp:638]: May be better to avoid these lots of negations and just use `success` instead of `hasFailed`.

Comment (henrysky) [reply src/core/modules/StarMgr.cpp]: fixed, thanks!
