### PR TITLE
Make objects split by cylinder projections wraparound appear on one side of the screen

### LINKED ISSUE #3437: Equirectangular Projection solar system bodies render bug at edge of screen
### Expected Behaviour
Did: Set Equirectangular Projection. Equatorial Mount on to fix the background stars in place. Sun, Moon, Planets on. Scaled to various multiplication factors. Timelapse on. 
Expected: all solar system bodies to appear to wraparound back to the right edge when they move to and cross the left edge to the right edge of the screen without visual anomalies. 

### Actual Behaviour
Got: horizontal lines across the screen whenever any solar system body goes to the edge of the screen.
Screenshot 2023-09-29 at 9 28 31 PM

Screenshot 2023-09-29 at 9 28 49 PM

### Steps to reproduce
See "Did" above. 

### System
* Stellarium version: 23.2
* Operating system: Mac OS "Sonoma" 14.0 
* Graphics Card: Apple M1
* Screen type (if applicable): Laptop

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/12773438/log.txt)

Thank you!

### PR DESCRIPTION
**Pull request by 10110111**
### Description

Some projections expand azimuth dimension over the width of the screen. This makes objects that are clipped by a side of the screen appear on the other side. But currently these objects remain single objects, which results in stretching over the whole distance between one side of the projection to the other.

This commit improves on this situation by making it possible to put an object completely on one side of the screen — the one where object's center resides. This loses the second half that should appear on the opposite side of the screen, but at least avoids the stretching artifacts.

Currently this is only applied to Cylinder projection and its derivatives. Others may be tweaked similarly in subsequent commits.

Fixes #3437

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Ubuntu 20.04
* Graphics Card: Intel UHD Graphics 620

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/core/StelProjectorClasses.hpp [hunk 1]
```diff
@@ -141,6 +143,8 @@ class StelProjectorCylinder : public StelProjector
 		SphericalCap cap(capN, capD);
 		return cap.intersects(cap1) && cap.intersects(cap2) && cap.intersects(cap3);
 	}
+
+	float objectCenterAzimuth = 0;
```
Comment (gzotti) [inline src/core/StelProjectorClasses.hpp:147]: Please add a comment what this is. It is confusing to possible new developers (or for ourselves, after 4 months or so :) that this is always astronomical azimuth (counted from North), regardless of the StelApp.flagAzimuthFromSouth setting, and that this is only used for a particular test (enableOneSideProjection()).

**Review by gzotti — APPROVED** [review]
OK for me, thanks!
