### PR TITLE
Fix ZL being killed by LP even at low Bortle values (fix #1489)

### LINKED ISSUE #1489: Zodiacal light practically invisible with the slightest light pollution
I'm not quite sure if this is really a bug (I've seen the comments in the code, and it seems intentional).

The zodiacal light is almost completely invisible if the light pollution is set to 2 or above. However, in reality, a Bortle 2 site would show a great deal of zodiacal light. I've seen it from a Bortle 4 area, quite impressive.

However, if one sets the extinction coefficient to 0.0, then the zodiacal light is displayed more realistically. Visible until about Bortle 4. Compare these two screenshots with light pollution set at 2:

With extinction = 0.2:
ext02

With extinction = 0.0:
ext00

I find it unrealistic.

### PR DESCRIPTION
**Pull request by Atque**
### Description
Currently, the light pollution almost completely hides the zodiacal light. This brings a better balance, so that users can use Bortle 2 and 3 skies, and still see some ZL without having to adjust it to crazy values (ZLi intensity = 5 or something).

Fixes #1489

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

**Test Configuration**:
Totally irrelevant.

**Please try it and see if you agree with my findings.**

## Checklist:
- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Thanks. The purpose of increasing brightness of ZL is mostly for adapting to screen environment and demonstration purposes, so at brightness 1 and in a dark room, the screen should approximately correspond to what you see outside. I will have a look  in the evening (need dark room...)

**Comment by Atque** [comment]
Yes I had to shut all blinds in my living room in order to test it. :) But the ZL is very faint in reality so that's fine.

**Comment by gzotti** [comment]
Indeed this may have been too radical. What about harmonizing the expression with that used for the Milky Way:

`float extinctionFactor=std::pow(0.4f , oneMag) * (1.1f-bortleIntensity*0.1f); `

I see some of ZL remaining at Bortle 4, which seems to be what you tried to achieve.

**Comment by Atque** [comment]
@gzotti That looks fine. It makes ZL a little less prominent with Bortle 3-4, but that's ok.

File: src/core/modules/ZodiacalLight.cpp [hunk 1]
```diff
@@ -250,7 +250,8 @@ void ZodiacalLight::draw(StelCore* core)
 
 			float oneMag=0.0f;
 			extinction.forward(vertAltAz, &oneMag);
-			float extinctionFactor=std::pow(0.4f , oneMag)/bortleIntensity; // drop of one magnitude: factor 2.5 or 40%, and further reduced by light pollution
+			float extinctionFactor=std::pow(0.4f , oneMag) * (1.1f-bortleIntensity*0.1f);// Drop of one magnitude: factor 2.5 or 40%, and further reduced by light pollution.
+			//float extinctionFactor=std::pow(0.4f , oneMag)/bortleIntensity; // Atque 2021-02-22: This makes the ZL invisible with the slightest LP.
```
Comment (gzotti) [inline src/core/modules/ZodiacalLight.cpp:254]: please remove the commented old line. The commit message will include your name/date/comment.
