### PR TITLE
Exclude outdated solar system objects

### LINKED ISSUE #1564: Exclude outdated comet data in ephemeris computations
### Expected Behaviour
Don't include comets beyond their valid time range in ephemeris computations

### Actual Behaviour
Found during trial around #1563: When searching for phenomena around Jupiter's moons in 2021, I can find conjunctions with comets with orbital data from the 1960s or so. 

### Steps to reproduce

Load 1000 comets data file. 
Use AstroCalc/Phenomena to search for phenomena around Jupiter's moons, e.g. June to September 2021.

### System
* Stellarium version: 0.21.0-RC1
* Operating system: Windows (irrelevant)
* Graphics Card: (irrelevant)

### PR DESCRIPTION
**Pull request by alex-w**
### Description
Excluding the Solar system objects with outdated data from ephemeris, positions and phenomena computations

Fixes #1564

### Screenshots (if appropriate):
v0.21.1:
stellarium-006

v0.21.1-122fe98:
stellarium-007

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?
Load 1000 comets data file.
Use AstroCalc/Phenomena (AstroCalc/Positions or AstroCalc/Ephemeris also) to search for phenomena around Jupiter's moons, e.g. June to September 2021.

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by axd1967** [comment]
The user would benefit from being informed about the problem, as it is not obvious that ephemeris data is outdated (as we can judge from several issues that are reported), especially for comets/asteroids, as these require the user to open the Solar System Editor, which is a tad hairy to manipulate. All too often the users **assume** that the data is always up-to-date, which is obviously NOT the case. So until an automatic update is possible, the user should be aware of the problem.

at least emit a `QWarning()` in the log file for each object that is outdated. 
It looks like this could be a good location for such a warning:
https://github.com/Stellarium/stellarium/blob/bc5ee585fc7b0b5f496a5afa340ac5c2cbbc25e3/src/core/modules/SolarSystem.cpp#L852

nicer but much more expensive is to (also) highlight outdated objected in the tabular GUIs (eg grey/italic?)

File: src/core/modules/Planet.hpp [hunk 1]
```diff
@@ -222,6 +222,7 @@ class Planet : public StelObject
 	virtual double getAngularSize(const StelCore* core) const Q_DECL_OVERRIDE;
 	virtual bool hasAtmosphere(void) {return atmosphere;}
 	virtual bool hasHalo(void) {return halo;}
+	bool hasValidData();
```
Comment (gzotti) [inline src/core/modules/Planet.hpp:225]: Please document what "valid" means in this context! Maybe rename to hasValidOrbitData() or hasValidPositionalData()

Comment (alex-w) [reply src/core/modules/Planet.hpp]: Good suggestion! 

Done.

File: src/core/modules/Planet.hpp [hunk 2]
```diff
@@ -222,6 +222,7 @@ class Planet : public StelObject
 	virtual double getAngularSize(const StelCore* core) const Q_DECL_OVERRIDE;
 	virtual bool hasAtmosphere(void) {return atmosphere;}
 	virtual bool hasHalo(void) {return halo;}
+	bool hasValidPositionalData();
```
Comment (gzotti) [inline src/core/modules/Planet.hpp:225]: Honestly, we need better documentation! The name is now better, but this should explain to other developers (or ourselves, in 4 months from now) why we need it, or what this test can be used for. E.g.

//! returns whether planet positions are valid and useful for the current simulation time. E.g. outdated orbital elements for Kepler orbits (beyond their orbit_good .ini file entries) may lead to invalid positions which should better not be used.

Comment (alex-w) [reply src/core/modules/Planet.hpp:227]: OK, you are right. I'm added notes also...

File: src/gui/AstroCalcDialog.cpp [hunk 3]
```diff
@@ -4473,6 +4480,19 @@ QMap<double, double> AstroCalcDialog::findClosestApproach(PlanetP& object1, Stel
 	QMap<double, double> separations;
 	QPair<double, double> extremum;
 
+	if (object2->getType()=="Planet")
```
Comment (gzotti) [inline src/gui/AstroCalcDialog.cpp:4483]: Hmm, do you also see the inefficiency?
For a simple date validity test you set the whole program state twice. 

Please do the following: extend
bool Planet::hasValidPositionalData(const double jde)
{
	if (pType<isObserver)
		return true;
	else if (orbitPtr && pType>=isArtificial)
		return static_cast<KeplerOrbit*>(orbitPtr)->objectDateValid(jde);
	else
		return false;
}

And then you can simply test here:

if  ( (!planet->hasValidPositionalData(stopJD)) || (!planet->hasValidPositionalData(startJD)) )
     return separations;  // empty result.

And probably this is not even what we need here? Imagine some object with orbit_good=100 (days)

You make an ephemeris for 250 days which enclose the orbit's validity range. The object would be excluded with the current solution! Maybe add a test for (startJD+stopJD)/2? Or sample every 50 days between startJD and stopJD? Or is there a limit or typical value for (stopJD-startJD)? If this is always something like 10 days, you could exclude the object if both dates are invalid.

Comment (alex-w) [reply src/gui/AstroCalcDialog.cpp:4483]: I've added JDE as parameter to reduce number of calls, but for second proposal I think it should be postponed to the future releases, because this subsystem should be refactored after pencil and paper works.

Comment (gzotti) [reply src/gui/AstroCalcDialog.cpp:4483]: OK. The inefficiency is solved. 
The next question is just what this function should do. Is this logic correct? Whenever at least one limit of the search interval is outside the validity range for the planet, the planet is discarded. I see a danger of another error. If you need to merge this now, leave a FIXME with this question for later, and maybe somebody reports an error. Else please don't merge, and let's solve this with better tests for the overlapping cases. (We may need to add some really simple date validity queries to the Planet.)

Comment (axd1967) [reply src/gui/AstroCalcDialog.cpp:4483]: please add the `QWarning()` logging, or some other warning mechanism. the `QWarning()` is not much asked, and will help if a user opens an issue; the log will explain what happened.

thank you!

Comment (alex-w) [reply src/gui/AstroCalcDialog.cpp:4484]: > The next question is just what this function should do. Is this logic correct? 

Yes, but I'll change it as first iteration of excluding the data.

**Comment by gzotti** [comment]
I looks much faster, but I may have found another bug.
stellarium-007
Eclipse between Jupiter and Neptune? With more than 3° separation this cannot be an occultation. Maybe Jupiter in transit as seen from Neptune? (Goto Neptune, but seen no transit). 
This is a separate issue though. 
Also, I think shadow transit checks can safely be reduced to the respective planet's moons, not things like comet and Jupiter. Yet another separate issue.

**Comment by alex-w** [comment]
I found today this issue too and this is puzzled me...

**Review by gzotti — APPROVED** [review]
I think the purpose of the branch is fulfilled. Newly found old weirdnesses which we now have found should be fixed in other issues/PRs. (0.21.1 finds the same things, so that's not a problem of this PR.)

**Comment by alex-w** [comment]
I'm work on fix of founded issue - just testing the fix right now in this branch

**Comment by alex-w** [comment]
OK, please check the fix

**Comment by gzotti** [comment]
OK. No more eclipses Neptune/Jupiter. 
However, running 0.21.1 and this branch side-by-side, the shadow transit events at Jupiter differ: One finds an event for Io, the other finds Europe, or vice versa. Both are correct in what they are finding, but just seem not to find all events. The search intervals in the phenomena tab overlap but are not identical, if that matters. (It should not!)

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
