### PR TITLE
Fixed prism rotation

### LINKED ISSUE #3281: Rotation prism in Ocular plugin
### Expected Behaviour
Ability rotate the prism in Oculars plugin via buttons on Oculars on-screen GUI or via hotkeys.

### Actual Behaviour
The prism cannot be rotated. 

Probably the bug was introduced 3 weeks ago in-depth refactoring the plugin.

### System
* Stellarium version: 23.2RC1

### PR DESCRIPTION
**Pull request by alex-w**
### Description
This pull request fixed issue for prism rotation in Oculars plugin.

Fixes #3281 (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: plugins/Oculars/src/Oculars.cpp [hunk 1]
```diff
@@ -1811,8 +1811,8 @@ void Oculars::paintCCDBounds()
 	double azimuth, elevation;
 	StelUtils::rectToSphe(&azimuth, &elevation, centerPos3d);
 	const auto derotate = Mat4f::rotation(Vec3f(0,0,1), azimuth) *
-						  Mat4f::rotation(Vec3f(0,1,0), -elevation) *
-						  Mat4f::rotation(Vec3f(1,0,0), ccd->chipRotAngle() * (M_PI/180));
+			      Mat4f::rotation(Vec3f(0,1,0), -elevation) *
```
Comment (10110111) [inline plugins/Oculars/src/Oculars.cpp:1814]: Why did you un-align these (and the similar lines below)?

Comment (alex-w) [reply plugins/Oculars/src/Oculars.cpp:1814]: Hmm... these lines aligned now for me. Did you used `stellarium-ide.xml` file for QtCreator?

Comment (10110111) [reply plugins/Oculars/src/Oculars.cpp:1814]: I don't use QtCreator with Stellarium. But IIRC, we use size-4 tabs, which then should make my indentation align the factors. Here's how your patch looks for me:

Screenshot_2023-06-23_21-29-09

Comment (alex-w) [reply plugins/Oculars/src/Oculars.cpp:1814]: Same place within QtCreator with our standard settings from `stellarium-ide.xml` file:
Снимок экрана 2023-06-24 в 00 39 32

Comment (10110111) [reply plugins/Oculars/src/Oculars.cpp:1814]: Wait, we have 8-position tabs?! So wasteful! And BTW, this is not mentioned in the coding style document, only in the XML file.
OK, I'll alter my Vim settings, and you please separate this reformatting from the PR, so that git-blame and git-show showed a clearer picture of what this PR really does.

**Review by 10110111 — APPROVED** [review]
LGTM provided that the two commits are squashed when merging.
